stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  script: echo "Building the app"

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to gitlab server"
  environment:
    name: staging
    url: https://github.com/vivekshrivastavaa    
    only:
  - master 

   gitlab to github

   ##Bipin again

